main: com.pwn9.PwnRaid.PwnRaid
name: PwnRaid
version: 0.6
author: tremor77
description: Start and manage villager raids.
website: http://pwn9.com
api-version: 1.14
permissions:
  pwnraid.*:
    description: gives all permissions of PwnRaid
    default: op
    children:
        pwnraid.bell: true